user:
  name:
    maximum: 50
  email:
    maximum: 255
  password:
    minimum: 6
post:
  per_page: 20
hot_user:
  number: 5
picture:
  fill_width: 118
  fill_height: 100
  limit_width: 800
  limit_height: 800
